### ISSUE TITLE
Fix `ln: /usr/bin/phantomjs: Operation not permitted` issue in OS X 

### ISSUE THREAD

**Issue by Payuing** [AnyISalIn/zhihu_fun#11]
The reason is [here](http://apple.stackexchange.com/questions/196224/unix-ln-s-command-not-permitted-in-osx-el-capitan-beta3)

Fix it by running this command
````bash
ln -sv /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
````

check if it's correctly configured by
````bash
which phantomjs
`````
If it prompts 
````bash
usr/local/bin/phantomjs
`````
Then you can have fun

**Comment by AnyISalIn** [comment]
on mac os , you can use `brew install phantomjs`
