### ISSUE TITLE
python3.4 run,py 报错

### ISSUE THREAD

**Issue by ghost** [AnyISalIn/zhihu_fun#12]
我低端玩家，不知道什么原因，都是看着步骤来的，可是还是报错。求大佬解决.

root@VM-23-248-debian:/usr/share/nginx/html/zhihu_fun# python3.4 run.py 
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from zhihu_fun.go import UrlGenerator, QuestionParser, basedir
  File "/usr/share/nginx/html/zhihu_fun/zhihu_fun/go.py", line 6, in <module>
    from .netlib.requests import my_session, _get_image
  File "/usr/share/nginx/html/zhihu_fun/zhihu_fun/netlib/requests.py", line 1, in <module>
    import requests
ImportError: No module named 'requests'
我安装requests..
root@VM-23-248-debian:/usr/share/nginx/html/zhihu_fun# pip2 install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
Cleaning up...
root@VM-23-248-debian:/usr/share/nginx/html/zhihu_fun# pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
Cleaning up...
但是还是运行报错，请帮忙解决，我用 pip install -r requirements.txt 安装过依赖了呀.

**Comment by AnyISalIn** [comment]
你用的还是 2.7 的库
```
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
```
