### ISSUE TITLE
记得做UTF8声明

### ISSUE THREAD

**Issue by bg4hkq** [AnyISalIn/zhihu_fun#7]
终端运行会报错，记得声明下UTF8

**Comment by AnyISalIn** [comment]
不会的，因为你不是 Python 3.。。

**Comment by bg4hkq** [comment]
哦哦，对，我还停留在2.7.

这个cookie什么格式啊？dict？怎么分隔？

**Comment by AnyISalIn** [comment]
直接字符串复制进去，就不用管了，代码里面做过切分的，README 里面有的
