### ISSUE TITLE
限制一下python的条件为3.5吧。用3.4跑不通，报JSONDecodeError无法import错误

### ISSUE THREAD

**Issue by c4fun** [AnyISalIn/zhihu_fun#8]
用3.4没有跑通，查了一下[manual](https://docs.python.org/3/library/json.html#json.JSONDecodeError)，
只有3.5有这个JSONDecodeError这个异常类型，3.4中没有，所以用python 3.4跑的时候也报错了。

  File "....../zhihu_fun/go.py", line 2, in <module>
    from json import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError'

**Comment by AnyISalIn** [comment]
https://github.com/AnyISalIn/zhihu_fun/commit/265df4151654013427f5cf6947d1d13dffe416f7 已修复
